version: '3'
services:
  frontend:
    image: pricemgp24/checkin-dashboard-frontend:v1.0
    ports:
      - "3000:3000"
  backend:
    image: pricemgp24/checkin-dashboard-backend:v1.0
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL:=mongodb://mongo:27017/checkins
  mongo:
    image: pricemgp24/mongo:v1.0
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
